[package]
name = "general_pub_sub"
version = "0.0.01"
authors = ["Dustin Ewan <dustineewan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
